name: 'Pyccel pytest commands generating fortran or c'
inputs:
  shell_cmd:
    description: 'Specifies the shell command (different for anaconda)'
    required: false
    default: 'bash'
  pytest_mark:
    description: 'Mark expression to exclude additional tests'
    required: false
    default: ''


runs:
  using: "composite"
  steps:
    - name: Test with pytest
      run: |
        which python
        python -m pytest -n auto -rXx -v -m "not (parallel or xdist_incompatible) and not (c or python) ${{ inputs.pytest_mark }}" --ignore=symbolic --ignore=ndarrays
        python -m pytest -rXx -v -m "xdist_incompatible and not parallel and not (c or python) ${{ inputs.pytest_mark }}" --ignore=symbolic --ignore=ndarrays
        pyccel-clean
        python -m pytest ndarrays/ -rXx
        pyccel-clean
      shell: ${{ inputs.shell_cmd }}
      working-directory: ./tests
