name: 'Posting in progress status'
inputs:
  ref:
    description: "The ref to post the status to"
    required: true
  installation_token:
    description: "The GitHub API token of the bot"
    required: true
  name:
    description: "The name of the workflow"
    required: true
outputs:
  check_id:
    description: "The ID of the check run"
    value: ${{ steps.post.outputs.check_id }}

runs:
  using: "composite"
  steps:
    - name: "Posting"
      run: |
        import requests
        headers = {"Accept": "application/vnd.github+json", "Authorization": f"Bearer ${{ inputs.installation_token }}", "X-GitHub-Api-Version": "2022-11-28"}
        data = {"name":"${{ inputs.name }}","head_sha":"${{ inputs.ref }}","status":"in_progress"}
        reply = requests.post("https://api.github.com/repos/${{ github.repository }}/check-runs", headers=headers, json=data)
        id = [r["id"] for r in reply.json()["check_runs"] if r["name"] == "${{ inputs.name }}"][-1]
        with open("${{ github.output }}", 'a') as f:
            print("check_id=",id,sep='')
      shell: python
