name: 'Posting in progress status'
inputs:
  ref:
    description: "The ref to post the status to"
    required: true
  installation_token:
    description: "The GitHub API token of the bot"
    required: true
  name:
    description: "The name of the workflow"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Posting"
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.installation_token }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          --url https://api.github.com/repos/${GITHUB_REPOSITORY}/check-runs \
          -d '{"name":"${{ inputs.name }}","head_sha":"${{ inputs.ref }}","status":"in_progress"}'
      shell: bash
