name: "Generate bot token"
inputs:
  bot_pem:
    description: "The private key which identfies the bot"
    required: true
outputs:
  installation_token:
    description: "The token which will allow you to authentificate as the GitHub app for 1 hour"
    value: ${{ steps.get_token.outputs.token }}

runs:
  using: "composite"
  steps:
    - run: |
        pip install jwt
      shell: bash
    - run: |
        echo "$PEM" > bot.pem
        cat bot.pem
      shell: bash
      env:
        PEM: ${{ inputs.bot_pem }}
    - run: |
        import jwt
        import time
        import os
        with open("bot.pem", "rb") as f:
            v = f.read()
            print(v[:10])
            signing_key = jwt.jwk_from_pem(v)
        with open("bot2.pem", "rb") as f:
            v = f.read()
            print(v[:10])
        # Issued at time
        # JWT expiration time (10 minutes maximum)
        # GitHub App's identifier
        payload = {'iat': int(time.time()), 'exp': int(time.time()) + 60, 'iss': 337566}

        # Create JWT
        with open("${{ github.output }}", 'a') as f:
            print("token=", jwt.JWT().encode(payload, signing_key, alg='RS256'), sep='', file = f)
      shell: python
      id: get_token
    - run:
        echo "${{ steps.get_token.outputs.token }}"
      shell: bash
