name: "Generate bot token"
inputs:
  bot_pem:
    description: "The private key which identfies the bot"
    required: true
outputs:
  installation_token:
    description: "The token which will allow you to authentificate as the GitHub app for 1 hour"
    value: ${{ steps.get_token.outputs.token }}

runs:
  using: "composite"
  steps:
    - run: |
        pip install jwt
      shell: bash
    - run: |
        import jwt
        import time
        signing_key = jwt.jwk_from_pem(b"""${{ inputs.bot_pem }}""")
        # Issued at time
        # JWT expiration time (10 minutes maximum)
        # GitHub App's identifier
        payload = {'iat': int(time.time()), 'exp': int(time.time()) + 60, 'iss': 337566}

        # Create JWT
        print("token=", jwt.JWT().encode(payload, signing_key, alg='RS256'), sep='', file = "${{ github.output }}")
      shell: python
      id: get_token
