name: "Generate bot token"
inputs:
  bot_pem:
    description: "The private key which identfies the bot"
    required: true
outputs:
  installation_token:
    description: "The token which will allow you to authentificate as the GitHub app for 1 hour"
    value: ${{ steps.get_token.outputs.token }}
  installation_token_expiry:
    description: "The expiration date of the token"
    value: ${{ steps.get_token.outputs.token_exp }}

runs:
  using: "composite"
  steps:
    - run: |
        pip install jwt requests
      shell: bash
    - run: |
        python -c "from ci_tools.bot_tools.github_api_interactions import get_authorization; t,d=get_authorization(); print('token=',t,sep=''); print('token_exp=',d,sep='')" >> ${{ github.output }}
      shell: bash
      id: get_token
      env:
        PEM: ${{ inputs.bot_pem }}
