name: "Generate bot token"
inputs:
  bot_pem:
    description: "The private key which identfies the bot"
    required: true
outputs:
  installation_token:
    description: "The token which will allow you to authentificate as the GitHub app for 1 hour"
    value: ${{ steps.get_token.outputs.token }}

runs:
  using: "composite"
  steps:
    - run: |
        pip install jwt requests
      shell: bash
    - run: |
        token=$(python -c "from ci_tools.bot_tools.github_api_interactions import get_authorization; print(get_authorization())")

        echo "token=${token}" >> ${{ github.output }}
      shell: bash
      id: get_token
      env:
        PEM: ${{ inputs.bot_pem }}
