name: "Generate bot token"
outputs:
  installation_token:
    description: "The token which will allow you to authentificate as the GitHub app for 1 hour"
    value: ${{ steps.get_token.outputs.token }}

runs:
  using: "composite"
  steps:
    - run: |
        from ci_tools.bot_tools.generate_jwt import get_jwt
        print("token=", get_jwt(${{ secrets.BOT_PEM }}), sep='', file = ${{ github.output }})
      shell: python
      id: get_token
