name: Clean up

on:
  check_run:
    types: completed

jobs:
  Post:
    runs-on: ubuntu-latest
    name: Report result

    steps:
      - name: Clean up
        run:
          python ci_tools/bot_clean_up.py
        shell: bash
