name: Deploy new version to PyPi

on:
  workflow_run:
    workflows: [Windows]
    types:
      - pickle_wheel

jobs:
  waitForWorklows:
    name: Wait for workflows
    runs-on: ubuntu-latest
    if: github.event.workflow_run.head_branch == 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Wait for workflows
        id: wait
        uses: smartcontractkit/chainlink-github-actions/utils/wait-for-workflows@main
        with:
          max-timeout: "900"
          polling-interval: "30"
          exclude-workflow-names: ""
          exclude-workflow-ids: ""
          github-token: ${{ github.token }}
        env:
          DEBUG: "true"

  deployVersion:
    runs-on: ubuntu-latest
    needs: [waitForWorklows]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        uses: ./.github/actions/linux_install
      - name: Update build
        run: |
          python -m pip install --upgrade build
      - name: Build and deploy
        run: |
          echo ${{ github.event.workflow_run.head_branch }}
          python3 -m build
          ls dist/*
          #python3 -m twine upload --repository pyccel dist/* -u $PYPI_USER -p $PYPI_PASSWORD
        shell: bash
