name: Doc Coverage Action

on:
  workflow_dispatch:
    inputs:
      python_version:
        required: true
        type: string
      ref:
        required: false
        type: string
      base:
        required: true
        type: string
      check_run_id:
        required: false
        type: string

jobs:

  DocumentationChecker:

    runs-on: ubuntu-latest
    name: Documentation Format

    steps:
      - name: Get ref 
        id: ref 
        run: | 
          ref = "${{ inputs.ref }}" or "${{ github.event.ref }}" 
          with open("${{ github.output }}", "a") as f: 
              print("ref=", ref, sep='', file=f) 
        shell: python
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.base }}
          path: base
      - uses: actions/checkout@v3
        with:
          path: compare
          ref: ${{ steps.ref.outputs.ref }}
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: "Generate token"
        id: token
        uses: ./base/.github/actions/generate_bot_token
        with:
          bot_pem: "${{ secrets.BOT_PEM }}"
          dir: "base"
      - name: "Post in progress"
        id: check_create
        uses: ./base/.github/actions/post_triggered
        with:
          ref: ${{ steps.ref.outputs.ref }}
          installation_token: ${{ steps.token.outputs.installation_token }}
          name: "Check documentation (docs)"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install docstr-coverage
          python -m pip install numpydoc
        shell: bash
      - name: Check doc coverage
        id: doc_coverage
        run: |
          echo "${{ github.event.pull_request.base.sha }}"
          docstr-coverage --skip-magic --skip-init base/pyccel 2>base_cov || true
          docstr-coverage --skip-magic --skip-init compare/pyccel 2>compare_cov || true
          python compare/ci_tools/summarise_doccoverage.py compare_cov base_cov $GITHUB_STEP_SUMMARY
        shell: bash
      - name: Check doc format
        id: doc_format
        run: |
          cd compare
          pip install .
          git fetch
          git diff origin/${{ inputs.base }}..HEAD --no-indent-heuristic --unified=0 --output=pull_diff.txt --no-color &>/dev/null
          touch objects.txt
          touch report.txt
          python ci_tools/list_docs_tovalidate.py pull_diff.txt objects.txt
          while read line; do    
            python -m numpydoc --validate $line >> report.txt 2>&1 || true 
          done < objects.txt
          cat report.txt
          python ci_tools/process_results.py report.txt $GITHUB_STEP_SUMMARY
          cd ..
        shell: bash
      - name: Final status
        if: always()
        id: status
        run:
          python ./base/ci_tools/check_success.py $GITHUB_OUTPUT steps.doc_coverage.outcome steps.doc_format.outcome
      - name: "Post completed"
        if: always()
        uses: ./base/.github/actions/post_completed
        with:
          installation_token: ${{ steps.token.outputs.installation_token }}
          run_id: ${{ steps.check_create.outputs.check_id }}
          status: ${{ steps.status.outcome }}
