name: Doc Coverage Action

on:
  workflow_dispatch:
    inputs:
      python_version:
        required: true
        type: string
      ref:
        required: false
        type: string
      base:
        required: true
        type: string
      check_run_id:
        required: false
        type: string

jobs:

  DocumentationChecker:

    runs-on: ubuntu-latest
    name: Documentation Format

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.base }}
          path: base
      - uses: actions/checkout@v3
        with:
          path: compare
          ref: ${{ inputs.ref || github.event.ref }}
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: "Setup"
        id: token
        run: |
          pip install jwt requests
          python base/ci_tools/setup_check_run.py
        env:
          PEM: ${{ secrets.BOT_PEM }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_CHECK_RUN_ID: ${{ inputs.check_run_id }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install docstr-coverage
          python -m pip install numpydoc
        shell: bash
      - name: Check doc coverage
        id: doc_coverage
        run: |
          echo "${{ github.event.pull_request.base.sha }}"
          docstr-coverage --skip-magic --skip-init base/pyccel 2>base_cov || true
          docstr-coverage --skip-magic --skip-init compare/pyccel 2>compare_cov || true
          python compare/ci_tools/summarise_doccoverage.py compare_cov base_cov $GITHUB_STEP_SUMMARY
        shell: bash
      - name: Check doc format
        id: doc_format
        run: |
          cd compare
          pip install .
          git fetch
          git diff ${{ inputs.base }}..HEAD --no-indent-heuristic --unified=0 --output=pull_diff.txt --no-color
          touch objects.txt
          touch report.txt
          python ci_tools/list_docs_tovalidate.py pull_diff.txt objects.txt
          while read line; do    
            python -m numpydoc --validate $line >> report.txt 2>&1 || true 
          done < objects.txt
          cat report.txt
          python ci_tools/process_results.py report.txt $GITHUB_STEP_SUMMARY
          cd ..
        shell: bash
      - name: "Post completed"
        if: always()
        run:
          python base/ci_tools/complete_check_run.py ${{ steps.doc_coverage.outcome }} ${{ steps.doc_format.outcome }}
        env:
          installation_token: ${{ steps.token.outputs.installation_token }}
          installation_token_exp: ${{ steps.token.outputs.installation_token_exp }}
          check_run_id: ${{ inputs.check_run_id }}
          status: ${{ steps.status.outcome }}
