name: Pyccel tests

on:
  pull_request:
    branches: [ master ]
    types: [ ready_for_review, synchronize ]

jobs:
  Linux:
    uses:
      ./.github/workflows/linux.yml
    with:
      python_version: 3.7

  Windows:
    uses:
      ./.github/workflows/windows.yml
    with:
      python_version: 3.7

  MacOSX:
    uses:
      ./.github/workflows/macosx.yml
    with:
      python_version: '3.10'

  CoverageChecker:

    needs: Linux
    uses:
      ./.github/workflows/coverage.yml
    with:
      python_version: 3.7
