name: Pyccel tests

on:
  pull_request:
    branches: [ master ]
    types: [ opened, ready_for_review, synchronize ]
  issue_comment:
    types: [ created ]

jobs:
  Bot:
    if: ${{ ( github.event_name == 'pull_request' && github.event.pull_request.draft == false ) || (github.event_name == 'issue_comment' && github.event.issue.pull_request ) }}
    runs-on: ubuntu-latest
    outputs:
      run_linux: ${{ steps.run_bot.outputs.run_linux }}
      run_windows: ${{ steps.run_bot.outputs.run_windows }}
      run_macosx: ${{ steps.run_bot.outputs.run_macosx }}
      run_coverage: ${{ steps.run_bot.outputs.run_coverage }}
      run_docs: ${{ steps.run_bot.outputs.run_docs }}
      run_pylint: ${{ steps.run_bot.outputs.run_pylint }}
      run_lint: ${{ steps.run_bot.outputs.run_lint }}
      run_spelling: ${{ steps.run_bot.outputs.run_spelling }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - id: run_bot
        run: |
          python ci_tools/bot_interaction.py $GITHUB_EVENT_PATH $GITHUB_OUTPUT
          echo "run_linux=false" >> "$GITHUB_OUTPUT"
          echo "run_windows=false" >> "$GITHUB_OUTPUT"
          echo "run_macosx=false" >> "$GITHUB_OUTPUT"
          echo "run_coverage=false" >> "$GITHUB_OUTPUT"
          echo "run_docs=false" >> "$GITHUB_OUTPUT"
          echo "run_pylint=false" >> "$GITHUB_OUTPUT"
          echo "run_lint=false" >> "$GITHUB_OUTPUT"
          echo "run_spelling=false" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}

  Linux:
    needs: Bot
    if: ${{ needs.Bot.outputs.run_linux }} == 'True'
    uses:
      ./.github/workflows/linux.yml
    with:
      python_version: 3.7

  Windows:
    needs: Bot
    if: ${{ needs.Bot.outputs.run_windows }} == 'True'
    uses:
      ./.github/workflows/windows.yml
    with:
      python_version: 3.7

  MacOSX:
    needs: Bot
    if: ${{ needs.Bot.outputs.run_macosx }} == 'True'
    uses:
      ./.github/workflows/macosx.yml
    with:
      python_version: '3.10'

  CoverageChecker:
    needs: [Bot, Linux]
    if: ${{ needs.Bot.outputs.run_coverage }} == 'True'
    uses:
      ./.github/workflows/coverage.yml
    with:
      python_version: 3.7

  DocumentationChecker:
    needs: Bot
    if: ${{ needs.Bot.outputs.run_docs }} == 'True'
    uses:
      ./.github/workflows/doc_coverage.yml
    with:
      python_version: 3.8
      base: ${{ github.event.pull_request.base.sha }}

  PythonLint:
    needs: Bot
    if: ${{ needs.Bot.outputs.run_pylint }} == 'True'
    uses:
      ./.github/workflows/lint.yml
    with:
      python_version: 3.8

  PyccelLint:
    needs: Bot
    if: ${{ needs.Bot.outputs.run_lint }} == 'True'
    uses:
      ./.github/workflows/pyccel_lint.yml
    with:
      python_version: 3.8
