name: Pyccel tests

on:
  pull_request:
    branches: [ master ]
    types: [ opened, ready_for_review, synchronize ]
  issue_comment:
    types: [ created ]

jobs:
  Bot:
    if: ${{ ( github.event_name == 'pull_request' ) || (github.event_name == 'issue_comment' && github.event.issue.pull_request ) }}
    runs-on: ubuntu-latest
    outputs:
      run_linux: ${{ steps.run_bot.outputs.run_linux }}
      run_windows: ${{ steps.run_bot.outputs.run_windows }}
      run_macosx: ${{ steps.run_bot.outputs.run_macosx }}
      run_coverage: ${{ steps.run_bot.outputs.run_coverage }}
      run_docs: ${{ steps.run_bot.outputs.run_docs }}
      run_pylint: ${{ steps.run_bot.outputs.run_pylint }}
      run_lint: ${{ steps.run_bot.outputs.run_lint }}
      run_spelling: ${{ steps.run_bot.outputs.run_spelling }}
      HEAD: ${{ steps.run_bot.outputs.HEAD }}
      REF: ${{ steps.run_bot.outputs.REF }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - id: run_bot
        run: |
          python ci_tools/bot_interaction.py $GITHUB_EVENT_PATH $GITHUB_OUTPUT ${{ github.run_id }}
        env:
          GH_TOKEN: ${{ github.token }}

  Linux:
    needs: Bot
    if: ${{ needs.Bot.outputs.run_linux == 'True' }}
    uses:
      ./.github/workflows/linux.yml
    with:
      python_version: 3.7

  Windows:
    needs: Bot
    if: ${{ needs.Bot.outputs.run_windows == 'True' }}
    uses:
      ./.github/workflows/windows.yml
    with:
      python_version: 3.7

  MacOSX:
    needs: Bot
    if: ${{ needs.Bot.outputs.run_macosx == 'True' }}
    uses:
      ./.github/workflows/macosx.yml
    with:
      python_version: '3.10'

  CoverageChecker:
    needs: [Bot, Linux]
    if: ${{ needs.Bot.outputs.run_coverage == 'True' }}
    uses:
      ./.github/workflows/coverage.yml
    with:
      python_version: 3.7

  DocumentationChecker:
    needs: Bot
    if: ${{ needs.Bot.outputs.run_docs == 'True' }}
    uses:
      ./.github/workflows/doc_coverage.yml
    with:
      python_version: 3.8
      base: ${{ needs.Bot.outputs.REF }}

  PythonLint:
    needs: Bot
    if: ${{ needs.Bot.outputs.run_pylint == 'True' }}
    uses:
      ./.github/workflows/lint.yml
    with:
      python_version: 3.8
      ref: ${{ needs.Bot.outputs.REF }}

  PyccelLint:
    needs: Bot
    if: ${{ needs.Bot.outputs.run_lint == 'True' }}
    uses:
      ./.github/workflows/pyccel_lint.yml
    with:
      python_version: 3.8
