name: Python Linting

on:
  workflow_dispatch:
    inputs:
      python_version:
        required: true
        type: string
      ref:
        required: true
        type: string

jobs:
  Linter:
    runs-on: ubuntu-latest
    name: Python best practices

    steps:
      - name: "Test secret"
        run: |
          echo "${{ secrets.BOT_PEM }}"
        shell: bash
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - run: |
          echo "$PEM" > bot2.pem
          cat bot2.pem
        shell: bash
        env:
          PEM: ${{ inputs.bot_pem }}
      - name: "Generate token"
        id: token
        uses: ./.github/actions/generate_bot_token
        with:
          bot_pem: "${{ secrets.BOT_PEM }}"
      - name: "Test output"
        run:
          echo "${{ steps.token.outputs.token }}"
      - name: "Post in progress"
        uses: ./.github/actions/post_triggered
        with:
          ref: ${{ inputs.ref }}
          installation_token: ${{ steps.token.outputs.token }}
          name: "Python linting"
      - name: Check branch
        run: |
          git branch
          git status
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint
        shell: bash
      - name: Pylint
        id: pylint
        run: |
            python -m pylint --rcfile=.pylintrc pyccel/parser/semantic.py > $GITHUB_STEP_SUMMARY
        shell: bash
      - name: "Post completed"
        if: always()
        uses: ./.github/actions/post_completed
        with:
          installation_token: ${{ steps.token.outputs.token }}
          run_id: ${{ github.run_id }}
          status: steps.pylint.output
