name: Python Linting
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Linter:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint
        shell: bash
      - name: Pylint
        run: |
            python -m pylint --rcfile=.pylintrc pyccel/parser/semantic.py > $GITHUB_STEP_SUMMARY
        shell: bash
