name: Wheel-pickled-installation

on:
  workflow_dispatch:
    inputs:
      python_version:
        required: true
        type: string
      ref:
        required: false
        type: string
      check_run_id:
        required: false
        type: string

jobs:
  Wheel-pickled-installation:
    runs-on: ubuntu-latest
    name: Deploy tests

    steps:
      - name: Get ref
        id: ref
        run: |
          ref = "${{ inputs.ref }}" or "${{ github.event.ref }}"
          with open("${{ github.output }}", "a") as f:
              print("ref=", ref, sep='', file=f)
        shell: python
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.ref.outputs.ref }}
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install dependencies
        uses: ./.github/actions/linux_install
      - name: Install Pyccel from wheel
        id: pickle
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m build
          python -m pip install dist/*.whl
        shell: bash
      - name: Check for existence of pickled files
        id: pickle_check
        uses: ./.github/actions/check_for_pickled
      - name: Final status
        if: always()
        id: status
        run:
          python ci_tools/check_success.py $GITHUB_OUTPUT steps.pickle.outcome steps.pickle_check.outcome
      - name: "Post completed"
        if: always()
        uses: ./.github/actions/post_completed
        with:
          installation_token: ${{ steps.token.outputs.installation_token }}
          run_id: ${{ steps.check_create.outputs.check_id }}
          status: ${{ steps.status.outcome }}
