name: Pickled-installation

on:
  workflow_dispatch:
    inputs:
      python_version:
        required: true
        type: string
      ref:
        required: true
        type: string
      editable_string:
        required: false
        type: string

jobs:
  Pickled-installation:
    runs-on: ubuntu-latest
    name: Deploy tests

    steps:
      - run: |
          echo "${{ inputs.python-version }}"
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: "Generate token"
        id: token
        uses: ./.github/actions/generate_bot_token
        with:
          bot_pem: "${{ secrets.BOT_PEM }}"
      - name: "Post in progress"
        id: check_create
        uses: ./.github/actions/post_triggered
        with:
          ref: ${{ inputs.ref }}
          installation_token: ${{ steps.token.outputs.installation_token }}
          name: "Unit tests on linux with anaconda (linux_anaconda)"
      - name: Install dependencies
        uses: ./.github/actions/linux_install
      - name: Install Pyccel
        id: pickle
        run: |
          python -m pip install --upgrade pip
          echo "python -m pip install ${{ inputs.editable_string }} ."
          python -m pip install ${{ inputs.editable_string }} .
        shell: bash
      - name: Check for existence of pickled files
        id: pickle_check
        uses: ./.github/actions/check_for_pickled
      - name: Final status
        if: always()
        id: status
        run:
          python ci_tools/check_success.py $GITHUB_OUTPUT steps.pickle.outcome steps.pickle_check.outcome
      - name: "Post completed"
        if: always()
        uses: ./.github/actions/post_completed
        with:
          installation_token: ${{ steps.token.outputs.installation_token }}
          run_id: ${{ steps.check_create.outputs.check_id }}
          status: ${{ steps.status.outcome }}
