name: Pyccel Linting

on:
  workflow_dispatch:
    inputs:
      python_version:
        required: true
        type: string
      ref:
        required: true
        type: string
      base:
        required: true
        type: string
      check_run_id:
        required: false
        type: string

jobs:
  Pyccel-Linter:
    runs-on: ubuntu-latest
    name: Best practices

    steps:
      - name: Get ref
        id: ref
        run: |
          ref = "${{ inputs.ref }}" or "${{ github.event.ref }}"
          with open("${{ github.output }}", "a") as f:
              print("ref=", ref, sep='', file=f)
        shell: python
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.ref.outputs.ref }}
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: "Setup"
        id: token
        run: |
          pip install jwt requests
          python ci_tools/setup_check_run.py
        env:
          PEM: ${{ secrets.BOT_PEM }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_CHECK_RUN_ID: ${{ inputs.check_run_id }}
      - name: Install dependencies
        uses: ./.github/actions/linux_install
      - name: Install Pyccel
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install pylint
        shell: bash
      - name: Collect diff information
        run: |
          git fetch
          git diff ${{ inputs.base }}..${{ steps.ref.outputs.ref }} --no-indent-heuristic --unified=0 --output=pull_diff.txt --no-color
        shell: bash
      - name: Lint
        id: lint
        run: |
          python ci_tools/check_slots.py $GITHUB_STEP_SUMMARY
          python ci_tools/check_pylint_commands.py . pull_diff.txt $GITHUB_STEP_SUMMARY
          cat $GITHUB_STEP_SUMMARY
        shell: bash
      - name: "Post completed"
        if: always()
        run:
          python ci_tools/complete_check_run.py ${{ steps.lint.outcome }}
        env:
          installation_token: ${{ steps.token.outputs.installation_token }}
          installation_token_exp: ${{ steps.token.outputs.installation_token_exp }}
