name: Pyccel Linting

on:
  workflow_dispatch:
    inputs:
      python_version:
        required: true
        type: string
      ref:
        required: true
        type: string
      base:
        required: true
        type: string

jobs:
  Pyccel-Linter:
    runs-on: ubuntu-latest
    name: Best practices

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: "Generate token"
        id: token
        uses: ./.github/actions/generate_bot_token
        with:
          bot_pem: "${{ secrets.BOT_PEM }}"
      - name: "Post in progress"
        id: check_create
        uses: ./.github/actions/post_triggered
        with:
          ref: ${{ steps.ref.outputs.ref }}
          installation_token: ${{ steps.token.outputs.installation_token }}
          name: "Python linting (pylint)"
      - name: Install dependencies
        uses: ./.github/actions/linux_install
      - name: Install Pyccel
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install pylint
        shell: bash
      - name: Collect diff information
        run: |
          git fetch
          git diff ${{ inputs.base }}..${{ inputs.ref }} --no-indent-heuristic --unified=0 --output=pull_diff.txt --no-color
        shell: bash
      - name: Lint
        id: lint
        run: |
          python ci_tools/check_slots.py $GITHUB_STEP_SUMMARY
          python ci_tools/check_pylint_commands.py . pull_diff.txt $GITHUB_STEP_SUMMARY
          cat $GITHUB_STEP_SUMMARY
        shell: bash
      - name: "Post completed"
        if: always()
        uses: ./.github/actions/post_completed
        with:
          installation_token: ${{ steps.token.outputs.installation_token }}
          run_id: ${{ steps.check_create.outputs.check_id }}
          status: ${{ steps.lint.outcome }}
