name: Pyccel Linting
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Pyccel-Linter:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install dependencies
        uses: ./.github/actions/linux_install
      - name: Install Pyccel
        run: |
            python -m pip install --upgrade pip
            python -m pip install .
        shell: bash
      - name: Lint
        run: |
            python ci_tools/check_slots.py $GITHUB_STEP_SUMMARY
        shell: bash
