name: Bot

on:
  pull_request_review:
    types: [ submitted ]

jobs:
  Bot:
    name: Update Review Stage
    if: (! github.event.pull_request.draft && github.event.review.user.type != 'Bot' )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - id: run_bot
        run: |
          python ci_tools/bot_review_react.py
        env:
          GH_TOKEN: ${{ github.token }}
