name: Spellcheck Action

on:
  workflow_dispatch:
    inputs:
      python_version:
        required: true
        type: string
      ref:
        required: false
        type: string
      check_run_id:
        required: false
        type: string

jobs:
  Spelling:
    runs-on: ubuntu-latest
    name: Documentation spellcheck

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref || github.event.ref }}
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: "Setup"
        id: token
        run: |
          pip install jwt requests
          python ci_tools/setup_check_run.py
        env:
          PEM: ${{ secrets.BOT_PEM }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_CHECK_RUN_ID: ${{ inputs.check_run_id }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install pyspelling
          python -m pip install pymdown-extensions
          # Install any additional libraries required: additional plugins, documentation building libraries, etc.
      - name: Install Aspell
        run: |
          sudo apt-get install aspell aspell-en
      - name: Spell check
        id: spelling
        run: |
           python -m pyspelling > misspellings.txt || true
           cat misspellings.txt
           python ci_tools/summarise_pyspelling.py misspellings.txt $GITHUB_STEP_SUMMARY
      - name: "Post completed"
        if: always()
        run:
          python ci_tools/complete_check_run.py ${{ steps.spelling.outcome }}
        env:
          installation_token: ${{ steps.token.outputs.installation_token }}
          installation_token_exp: ${{ steps.token.outputs.installation_token_exp }}
          check_run_id: ${{ inputs.check_run_id }}
