name: Spellcheck Action

on:
  workflow_dispatch:
    inputs:
      python_version:
        required: true
        type: string
      ref:
        required: false
        type: string
      check_run_id:
        required: false
        type: string

jobs:
  Spelling:
    runs-on: ubuntu-latest
    name: Documentation spellcheck

    steps:
      - name: Get ref
        id: ref
        run: |
          ref = "${{ inputs.ref }}" or "${{ github.event.ref }}"
          with open("${{ github.output }}", "a") as f:
              print("ref=", ref, sep='', file=f)
        shell: python
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.ref.outputs.ref }}
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: "Generate token"
        id: token
        uses: ./.github/actions/generate_bot_token
        with:
          bot_pem: "${{ secrets.BOT_PEM }}"
      - name: "Post in progress"
        id: check_create
        uses: ./.github/actions/post_triggered
        with:
          ref: ${{ steps.ref.outputs.ref }}
          installation_token: ${{ steps.token.outputs.installation_token }}
          name: "Spelling verification (spelling)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install pyspelling
          python -m pip install pymdown-extensions
          # Install any additional libraries required: additional plugins, documentation building libraries, etc.
      - name: Install Aspell
        run: |
          sudo apt-get install aspell aspell-en
      - name: Spell check
        id: spelling
        run: |
           python -m pyspelling > misspellings.txt || true
           cat misspellings.txt
           python ci_tools/summarise_pyspelling.py misspellings.txt $GITHUB_STEP_SUMMARY
      - name: "Post completed"
        if: always()
        uses: ./.github/actions/post_completed
        with:
          installation_token: ${{ steps.token.outputs.installation_token }}
          run_id: ${{ steps.check_create.outputs.check_id }}
          status: ${{ steps.spelling.outcome }}
